image: cirrusci/flutter:latest

variables:

before_script:
  - flutter config --enable-web
  - flutter pub get
  - flutter packages pub run build_runner build --delete-conflicting-outputs

pages:
  stage: deploy
  script:
    - flutter build web
    - echo -e "<script>(function () {document.write('<base href=\"' + document.location.pathname + '\" />');}());</script>\n$(cat build/web/index.html)" > build/web/index.html
    - cp -r build/web public
  artifacts:
    paths:
      - public
  only:
    - staging