name: som
description: Smart Offer Management
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  annotations:
    path:
      ./lib/playground/domain_generator/annotations
  chopper: ^8.5.0
  url_launcher: ^6.3.2
  nb_utils: ^7.2.0
  intl: ^0.20.2
  http: ^1.6.0
  mobx: ^2.6.0
  flutter_mobx: ^2.3.0
  provider: ^6.1.5+1
  shared_preferences: ^2.5.4
  # snaplist: 0.1.8
  flutter_svg: ^2.2.3

  #  geocoder: 0.2.1
  google_maps_flutter: ^2.14.0
  #  razorpay_flutter: ^1.2.5
  #  lipsum: 1.0.1
  #  charts_flutter: ^0.10.0
  cached_network_image: ^3.4.1
  uuid: ^4.5.2
  file_picker: ^10.3.8
  #  geohash: ^0.2.1


  #Dimond kit

  # Cloud Storage #
  # expandable_bottom_sheet and multi_image_picker removed (unused/discontinued)

  #clustering_google_maps: ^0.1.2
  #image_picker_gallery_camera: 0.1.6



  flutter_localizations:
    sdk: flutter

  dropdown_search: ^6.0.2
  json_annotation: ^4.9.0


  # refactor to ednet_design_system
  som_manager:
    path: lib/generated

  ednet_core:
    path: /Users/slavisam/projects/cms/packages/core
  #  #    git:
  #  #      url: git@github.com:ednet-dev/ednet_core.git
  #  #      ref: main

  #  ednet_semantics:
  #    path: ../../projects/ednet_semantics
  #  #    git:
  #  #      url: git@github.com:ednet-dev/ednet_semantics.git
  #  #      ref: main

  openapi:
    path: ./openapi

  freezed_annotation: ^3.1.0
  fpdart: ^1.2.0

  logger: ^2.6.2
  dio: ^5.9.0
  curl_logger_dio_interceptor: ^1.0.1
  beamer: ^1.7.0
  connectivity_plus: ^7.0.0
  supabase_flutter: ^2.12.0
  built_collection: ^5.1.1

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mobx_codegen: ^2.7.6
  build_runner: ^2.10.5
  chopper_generator: ^8.5.0
  json_serializable: ^6.11.4
  generators:
    path: ./lib/playground/domain_generator/generators

  #flutter packages pub run build_runner build --delete-conflicting-outputs

flutter:

  uses-material-design: true

  assets:
    - assets/
    - images/
    - images/som/
    - images/som/icons/
    - lang/en.json
    - lang/de.json
    - lang/sr.json

    # som
    - images/som/
    - assets/design_system/wizards/
    - assets/design_system/
    - assets/design_system/ads/
    - assets/design_system/auth/
    - assets/design_system/backgrounds/
    - assets/design_system/common/
    - assets/design_system/empty_states/
    - assets/design_system/illustrations/
    - assets/design_system/inquiry/
    - assets/design_system/interaction/
    - assets/design_system/offers/
    - assets/design_system/patterns/
    - assets/design_system/statistics/
    - assets/design_system/subscription/
    - assets/design_system/wizards/
  fonts:
    - family: Andina
      fonts:
        - asset: fonts/andina.ttf

    - family: Regular
      fonts:
        - asset: fonts/googlesansregular.ttf

    - family: Medium
      fonts:
        - asset: fonts/googlesansmedium.ttf

    - family: Semibold
      fonts:
        - asset: fonts/googlesansmedium.ttf

    - family: Bold
      fonts:
        - asset: fonts/googlesansebold.ttf

    - family: Roboto
      fonts:
        - asset: fonts/robotoregular.ttf
          weight: 400
        - asset: fonts/robotomedium.ttf
          weight: 500
