name: som
description: Smart Offer Management
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=3.5.0-180.3.beta <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  annotations:
    path:
      ./lib/playground/domain_generator/annotations
  chopper: ^8.4.0
  japx: ^2.0.5
  cupertino_icons: ^1.0.5
  url_launcher: ^6.1.8
  nb_utils: ^7.2.0
  animations: ^2.0.7
  intl: ^0.20.2
  http: ^1.6.0
  html: ^0.15.1
  share: ^2.0.4
  mobx: ^2.1.3
  flutter_mobx: ^2.0.6+5
  provider: ^6.0.5
  flutter_vector_icons: ^2.0.0
  package_info: ^2.0.2
  shared_preferences: ^2.0.17
  simple_animations: ^5.0.0+3
  # snaplist: 0.1.8
  flutter_svg: ^2.2.3
  flutter_slidable: ^4.0.3
  flutter_staggered_grid_view: ^0.7.0

  google_sign_in: ^7.2.0
  geolocator: ^14.0.2
  webview_flutter: ^4.0.2
  #  geocoder: 0.2.1
  google_maps_flutter: ^2.2.3
  #  razorpay_flutter: ^1.2.5
  signature: ^6.3.0
  liquid_swipe: ^3.0.0
  #  lipsum: 1.0.1
  flutter_colorpicker: ^1.0.3
  video_player: ^2.5.1
  #  charts_flutter: ^0.10.0
  flutter_reaction_button: ^3.0.0+3
  lottie: ^3.3.2
  showcaseview: ^5.0.1
  cached_network_image: ^3.2.3
  local_auth: ^3.0.0
  dots_indicator: ^4.0.1
  image_picker: ^1.2.1
  flutter_rating_bar: ^4.0.1
  percent_indicator: ^4.2.2
  carousel_slider: ^5.1.1
  uuid: ^4.5.2
  modal_bottom_sheet: ^3.0.0
  #  geohash: ^0.2.1


  #Dimond kit
  sleek_circular_slider: ^2.0.1
  sliding_up_panel: ^2.0.0+1

  # Cloud Storage #
  expandable_bottom_sheet: ^1.1.1+1
  multi_image_picker: ^4.8.1

  #clustering_google_maps: ^0.1.2
  #image_picker_gallery_camera: 0.1.6

  fl_chart: ^1.1.1
  syncfusion_flutter_charts: ^32.1.22

  flutter_localizations:
    sdk: flutter

  dropdown_search: ^6.0.2
  json_annotation: ^4.8.0

  google_mobile_ads: ^7.0.0

  # refactor to ednet_design_system
  som_manager:
    path: lib/generated

  ednet_core:
    path: /Users/slavisam/projects/cms/packages/core
  #  #    git:
  #  #      url: git@github.com:ednet-dev/ednet_core.git
  #  #      ref: main

  #  ednet_semantics:
  #    path: ../../projects/ednet_semantics
  #  #    git:
  #  #      url: git@github.com:ednet-dev/ednet_semantics.git
  #  #      ref: main

  openapi:
    path: ./openapi

  freezed_annotation: ^3.1.0
  freezed: ^3.1.0
  fpdart: ^1.2.0
  functional_widget: ^0.10.1

  logger: ^2.6.2
  dio: ^5.9.0
  pretty_dio_logger: ^1.4.0
  curl_logger_dio_interceptor: ^1.0.1
  beamer: ^1.5.3
  jwt_decode: ^0.3.1
  connectivity_plus: ^7.0.0
  readmore: ^3.0.0

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  built_collection: ^5.1.1
  mobx_codegen: ^2.1.1
  build_runner: ^2.3.3
  chopper_generator: ^8.2.0
  json_serializable: ^6.6.0
  generators:
    path: ./lib/playground/domain_generator/generators

  #flutter packages pub run build_runner build --delete-conflicting-outputs

flutter:

  uses-material-design: true

  assets:
    - assets/
    - images/
    - images/som/
    - images/som/icons/
    - lang/en.json
    - lang/de.json
    - lang/sr.json

    # som
    - images/som/
  fonts:
    - family: Andina
      fonts:
        - asset: fonts/andina.ttf

    - family: Regular
      fonts:
        - asset: fonts/googlesansregular.ttf

    - family: Medium
      fonts:
        - asset: fonts/googlesansmedium.ttf

    - family: Semibold
      fonts:
        - asset: fonts/googlesansmedium.ttf

    - family: Bold
      fonts:
        - asset: fonts/googlesansebold.ttf

    - family: Roboto
      fonts:
        - asset: fonts/robotoregular.ttf
          weight: 400
        - asset: fonts/robotomedium.ttf
          weight: 500
