name: som
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.3
  url_launcher: ^6.0.3
  nb_utils: ^4.2.11
  google_fonts: ^2.1.0
  animations: ^2.0.0
  intl: ^0.17.0
  http: ^0.13.3
  firebase_core: ^1.2.0
  firebase_crashlytics: ^2.0.4
  google_mobile_ads: ^0.12.2
  html: ^0.15.0
  share: ^2.0.4
  mobx: ^2.0.6+1
  flutter_mobx: ^2.0.4
  provider: ^6.0.2
  flutter_vector_icons: ^1.0.0
  package_info: ^2.0.2

  simple_animations: ^3.1.1
  # snaplist: 0.1.8
  flutter_svg: ^0.22.0
  flutter_slidable: 0.6.0
  flutter_staggered_grid_view: ^0.4.0
  flutter_staggered_animations: 1.0.0

  google_sign_in: ^5.0.4
  geolocator: ^7.0.3
  webview_flutter: ^2.0.8
  #  geocoder: 0.2.1
  google_maps_flutter: ^2.0.6
  #  razorpay_flutter: ^1.2.5
  signature: ^4.1.1
  liquid_swipe: ^2.1.0
  #  lipsum: 1.0.1
  flutter_colorpicker: ^0.6.0
  clippy_flutter: ^2.0.0-nullsafety.1
  video_player: ^2.1.4
  #  charts_flutter: ^0.10.0
  flutter_reaction_button: ^1.0.8
  lottie: ^1.0.1
  showcaseview: ^1.0.0
  cached_network_image: ^3.0.0
  local_auth: ^1.1.6
  dots_indicator: ^2.0.0
  image_picker: ^0.8.4
  file_picker: ^4.0.2
  flutter_local_notifications: ^8.2.0
  flutter_rating_bar: ^4.0.0
  percent_indicator: ^3.0.1
  carousel_slider: ^4.0.0-nullsafety.0

  #  geohash: ^0.2.1


  #Dimond kit
  sleek_circular_slider: ^2.0.0
  sliding_up_panel: ^2.0.0+1

  # Cloud Storage #
  expandable_bottom_sheet: ^1.0.0+2
  multi_image_picker: ^4.8.00

  #clustering_google_maps: ^0.1.2
  #image_picker_gallery_camera: 0.1.6

  fl_chart: ^0.40.0
  syncfusion_flutter_charts: ^19.1.67

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.0.1+3
  build_runner: ^2.0.4
  #flutter packages pub run build_runner build --delete-conflicting-outputs

flutter:

  uses-material-design: true

  assets:
    - assets/
    - images/LikeButton/image/grey.jpg
    - images/widgets/materialWidgets/mwAppStructureWidgets/BottomNavigation/
    - images/widgets/materialWidgets/mwAppStructureWidgets/TabBar/
    - images/widgets/materialWidgets/mwInputSelectionWidgets/Checkbox/
    - images/widgets/materialWidgets/mwInputSelectionWidgets/switch/
    - images/widgets/materialWidgets/mwInformationDisplayWidgets/cards/
    - images/widgets/materialWidgets/mwInformationDisplayWidgets/gridview/
    - images/widgets/materialWidgets/mwInputSelectionWidgets/Checkbox/
    - images/widgets/materialWidgets/mwInputSelectionWidgets/switch/
    - images/widgets/materialWidgets/mwLayoutWidgtes/MWUserAccountDrawerHeaderWidget/
    - images/widgets/materialWidgets/mwDialogAlertPanelWidgets/
    - images/widgets/materialWidgets/mwLayoutWidgtes/MWListTile/
    - images/widgets/cupertinoWidgets/
    - images/widgets/materialWidgets/mwInformationDisplayWidgets/listView/
    - images/widgets/animationAndMotionWidgets/
    - images/widgets/paintingAndEffectWidgets/opacity/
    - images/widgets/interactionModelWidgets/
    - images/defaultTheme/
    - images/defaultTheme/category/
    - images/defaultTheme/banner/
    - assets/defaultTheme/
    - assets/cricket_data/
    - lang/en.json
    - lang/de.json
    - lang/sr.json

    # som
    - images/som/
  fonts:
    - family: Andina
      fonts:
        - asset: fonts/andina.ttf

    - family: Regular
      fonts:
        - asset: fonts/googlesansregular.ttf

    - family: Medium
      fonts:
        - asset: fonts/googlesansmedium.ttf

    - family: Semibold
      fonts:
        - asset: fonts/googlesansmedium.ttf

    - family: Bold
      fonts:
        - asset: fonts/googlesansebold.ttf

