name: som
description: Smart offer management

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  nb_utils: ^4.0.6
  mobx: ^1.2.1+2
  flutter_mobx: ^1.1.0+2
  package_info: ^2.0.0
  url_launcher: ^6.0.2
  intl: ^0.17.0
  flutter_vector_icons: ^1.0.0
  google_maps_flutter: ^2.0.1
  cached_network_image: ^2.3.1
  lipsum: 1.0.1
  flutter_svg: ^0.21.0-nullsafety.0
  google_mobile_ads: ^0.11.0+2
  share: ^2.0.1
  flutter_staggered_animations: 1.0.0
  google_fonts: 2.0.0
  html: ^0.15.0
  geohash: ^0.2.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mobx_codegen: ^1.1.2
  build_runner: ^1.11.5

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/
    - images/app/icons/
    - images/app/
    - images/app/ic_rate_app.png
    - images/defaultTheme/
    - images/defaultTheme/category/
    - images/defaultTheme/banner/
    - images/
    - images/som/
    - images/som/connecting/
    - images/som/descission/
    - images/som/independent/
    - images/som/inquiry/
    - images/som/offer/
    - images/som/savings/
    - images/som/simple/
    - images/som/sustainable/
    - assets/integrations/map_point.json
    - assets/defaultTheme/
    - lang/en.json
    - lang/hi.json

  fonts:
    - family: Andina
      fonts:
        - asset: fonts/andina.ttf

    - family: Regular
      fonts:
        - asset: fonts/googlesansregular.ttf

    - family: Medium
      fonts:
        - asset: fonts/googlesansmedium.ttf

    - family: Semibold
      fonts:
        - asset: fonts/googlesansmedium.ttf

    - family: Bold
      fonts:
        - asset: fonts/googlesansebold.ttf