name: som
description: A new Flutter application.
version: 1.0.0+1

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  annotations:
    path:
      ./lib/domain/domain_generator/annotations/
  chopper: ^4.0.6
  chopper_built_value: ^1.0.0
  japx: ^2.0.4
  cupertino_icons: ^1.0.5
  url_launcher: ^6.1.5
  nb_utils: ^4.6.20
  google_fonts: ^3.0.1
  animations: ^2.0.3
  intl: ^0.17.0
  http: ^0.13.5
  html: ^0.15.0
  share: ^2.0.4
  mobx: ^2.0.7+5
  flutter_mobx: ^2.0.6+1
  provider: ^6.0.3
  flutter_vector_icons: ^1.0.0
  package_info: ^2.0.2
  shared_preferences: ^2.0.15
  simple_animations: ^4.2.0
  # snaplist: 0.1.8
  flutter_svg: ^1.1.3
  flutter_slidable: ^2.0.0
  flutter_staggered_grid_view: ^0.6.2

  google_sign_in: ^5.4.1
  geolocator: ^9.0.1
  webview_flutter: ^3.0.4
  #  geocoder: 0.2.1
  google_maps_flutter: ^2.1.10
  #  razorpay_flutter: ^1.2.5
  signature: ^5.1.0
  liquid_swipe: ^3.0.0
  #  lipsum: 1.0.1
  flutter_colorpicker: ^1.0.3
  clippy_flutter: ^1.1.1
  video_player: ^2.4.6
  #  charts_flutter: ^0.10.0
  flutter_reaction_button: ^2.0.1+2
  lottie: ^1.4.1
  showcaseview: ^1.1.8
  cached_network_image: ^3.2.1
  local_auth: ^2.1.2
  dots_indicator: ^2.1.0
  image_picker: ^0.8.5+3
  file_picker: ^5.0.1
  flutter_local_notifications: ^9.7.0
  flutter_rating_bar: ^4.0.1
  percent_indicator: ^4.2.2
  carousel_slider: ^4.1.1
  modal_bottom_sheet: ^2.1.0
  #  geohash: ^0.2.1


  #Dimond kit
  sleek_circular_slider: ^2.0.1
  sliding_up_panel: ^2.0.0+1

  # Cloud Storage #
  expandable_bottom_sheet: ^1.1.1+1
  multi_image_picker: ^4.8.1

  #clustering_google_maps: ^0.1.2
  #image_picker_gallery_camera: 0.1.6

  fl_chart: ^0.55.1
  syncfusion_flutter_charts: ^20.2.43

  flutter_localizations:
    sdk: flutter

  dropdown_search: ^5.0.2
  json_annotation: ^4.6.0

  google_mobile_ads: ^2.0.0

  ednet_component_library:
    git:
      url: git@gitlab.com:ednet/supernova-material.git
      ref: design_system

  ednet_core:
    git:
      url: git@github.com:ednet-dev/ednet_core.git
      ref: main

  ednet_semantics:
    git:
      url: git@github.com:ednet-dev/ednet_semantics.git
      ref: main

  openapi:
    path: ./openapi

  freezed_annotation: ^2.1.0
  logger: ^1.1.0
  dio: '>=4.0.1 <5.0.0'
  pretty_dio_logger: ^1.1.1
  curl_logger_dio_interceptor: ^0.0.3
  beamer: ^1.5.0
  jwt_decode: ^0.3.1
  connectivity:

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.0.7
  build_runner: ^2.2.0
  chopper_generator: ^4.0.6
  json_serializable: ^6.3.1
  generators:
    path: ./lib/domain/domain_generator/generators/
  freezed: ^2.1.0+1

  #flutter packages pub run build_runner build --delete-conflicting-outputs

flutter:

  uses-material-design: true

  assets:
    - assets/
    - images/
    - images/som/
    - images/som/icons/
    - lang/en.json
    - lang/de.json
    - lang/sr.json

    # som
    - images/som/
  fonts:
    - family: Andina
      fonts:
        - asset: fonts/andina.ttf

    - family: Regular
      fonts:
        - asset: fonts/googlesansregular.ttf

    - family: Medium
      fonts:
        - asset: fonts/googlesansmedium.ttf

    - family: Semibold
      fonts:
        - asset: fonts/googlesansmedium.ttf

    - family: Bold
      fonts:
        - asset: fonts/googlesansebold.ttf

    - family: Roboto
      fonts:
        - asset: fonts/robotomedium.ttf
        - asset: fonts/robotoregular.ttf
        - weight: 400