name: som
description: Smart Offer Management
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  annotations:
    path:
      ./lib/playground/domain_generator/annotations
  chopper: ^6.0.0
  japx: ^2.0.5
  cupertino_icons: ^1.0.5
  url_launcher: ^6.1.8
  nb_utils: ^5.0.0
  animations: ^2.0.7
  intl: ^0.17.0
  http: ^0.13.5
  html: ^0.15.1
  share: ^2.0.4
  mobx: ^2.1.3
  flutter_mobx: ^2.0.6+5
  provider: ^6.0.5
  flutter_vector_icons: ^2.0.0
  package_info: ^2.0.2
  shared_preferences: ^2.0.17
  simple_animations: ^5.0.0+3
  # snaplist: 0.1.8
  flutter_svg: ^1.1.6
  flutter_slidable: ^2.0.0
  flutter_staggered_grid_view: ^0.6.2

  google_sign_in: ^5.4.4
  geolocator: ^9.0.2
  webview_flutter: ^4.0.2
  #  geocoder: 0.2.1
  google_maps_flutter: ^2.2.3
  #  razorpay_flutter: ^1.2.5
  signature: ^5.3.0
  liquid_swipe: ^3.0.0
  #  lipsum: 1.0.1
  flutter_colorpicker: ^1.0.3
  video_player: ^2.5.1
  #  charts_flutter: ^0.10.0
  flutter_reaction_button: ^2.0.1+2
  lottie: ^2.2.0
  showcaseview: ^2.0.0+1
  cached_network_image: ^3.2.3
  local_auth: ^2.1.3
  dots_indicator: ^2.1.0
  image_picker: ^0.8.6+1
  file_picker: ^5.2.5
  flutter_local_notifications: ^13.0.0
  flutter_rating_bar: ^4.0.1
  percent_indicator: ^4.2.2
  carousel_slider: ^4.2.1
  uuid: ^3.0.7
  modal_bottom_sheet: ^2.1.2
  #  geohash: ^0.2.1


  #Dimond kit
  sleek_circular_slider: ^2.0.1
  sliding_up_panel: ^2.0.0+1

  # Cloud Storage #
  expandable_bottom_sheet: ^1.1.1+1
  multi_image_picker: ^4.8.1

  #clustering_google_maps: ^0.1.2
  #image_picker_gallery_camera: 0.1.6

  fl_chart: ^0.60.0
  syncfusion_flutter_charts: ^20.4.44

  flutter_localizations:
    sdk: flutter

  dropdown_search: ^5.0.5
  json_annotation: ^4.8.0

  google_mobile_ads: ^2.3.0

  # refactor to ednet_design_system
  ednet_component_library:
    git:
      url: git@gitlab.com:ednet/supernova-material.git
      ref: design_system

  som_manager:
    path: lib/generated

  ednet_cms:
    path: ../../ednet/cms/packages/ednet_cms

  #  #    git:
  #  #      url: git@github.com:ednet-dev/ednet_core.git
  #  #      ref: main

  #  ednet_semantics:
  #    path: ../../projects/ednet_semantics
  #  #    git:
  #  #      url: git@github.com:ednet-dev/ednet_semantics.git
  #  #      ref: main

  openapi:
    path: ./openapi

  freezed_annotation: ^2.2.0
  freezed: ^2.3.2
  fpdart: ^0.4.0
  functional_widget: ^0.10.1

  logger: ^1.1.0
  dio: '>=4.0.1 <5.0.0'
  pretty_dio_logger: ^1.1.1
  curl_logger_dio_interceptor: ^0.0.3
  beamer: ^1.5.3
  jwt_decode: ^0.3.1
  connectivity:
  readmore: ^2.2.0

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.1.1
  build_runner: ^2.3.3
  chopper_generator: ^6.0.0
  json_serializable: ^6.6.0
  generators:
    path: ./lib/playground/domain_generator/generators

  #flutter packages pub run build_runner build --delete-conflicting-outputs

flutter:

  uses-material-design: true

  assets:
    - assets/
    - images/
    - images/som/
    - images/som/icons/
    - lang/en.json
    - lang/de.json
    - lang/sr.json

    # som
    - images/som/
  fonts:
    - family: Andina
      fonts:
        - asset: fonts/andina.ttf

    - family: Regular
      fonts:
        - asset: fonts/googlesansregular.ttf

    - family: Medium
      fonts:
        - asset: fonts/googlesansmedium.ttf

    - family: Semibold
      fonts:
        - asset: fonts/googlesansmedium.ttf

    - family: Bold
      fonts:
        - asset: fonts/googlesansebold.ttf

    - family: Roboto
      fonts:
        - asset: fonts/robotomedium.ttf
        - asset: fonts/robotoregular.ttf
        - weight: 400