name: som_api
description: Dart Frog API for SOM
version: 0.1.0
publish_to: none

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  dart_frog: ^1.1.0
  dart_jsonwebtoken: ^3.3.1
  uuid: ^4.4.0
  crypto: ^3.0.3
  logging: ^1.2.0
  intl: ^0.20.2
  collection: ^1.18.0
  path: ^1.9.0
  mime: ^2.0.0
  http_parser: ^4.0.2
  supabase: ^2.5.6
  som_manager:
    path: ../lib/generated
  ednet_core:
    path: /Users/slavisam/projects/cms/packages/core
  mailer: ^6.6.0
  pdf: ^3.11.3

dev_dependencies:
  dart_frog_test: ^0.1.2
  test: ^1.25.5
  lints: ^6.0.0
